window.CHAPTERS_CONFIG = [
  { "text": "سرورق", "link": "front-cover" },
  { "text": "صفحہ عنوان", "link": "title-page" },
  { "text": "یہ وہ گوہر شاہی ہیں", "link": "this-is-that-gohar-shahi" },
  { "text": "پیش لفظ", "link": "preface" },
  { "text": "دیباچہ از ریاض احمد گوھر شاہی", "link": "introduction-by-ra-gohar-shahi" },
  { "text": "انسان ازل سے ابد تک", "link": "man-since-creation-to-infinite" },
  { "text": "دنیا میں انسان کی بنیاد", "link": "roots-of-man-in-the-world" },
  { "text": "تذکرۂ نفس", "link": "the-doctrine-of-nafs-(the-self)" },
  { "text": "لطیفہ قلب", "link": "the-subtlety-of-qalb" },
  { "text": "انسانی روح", "link": "the-human-soul" },
  { "text": "لطیفہ سری", "link": "the-subtlety-of-sirri-(secret)" },
  { "text": "لطیفہ خفی", "link": "the-subtlety-of-khafi-(arcane)" },
  { "text": "لطیفہ اخفیٰ", "link": "the-subtlety-of-akhfa-(obscure)" },
  { "text": "لطیفہ انا", "link": "the-subtlety-of-ana" },
  { "text": "انسانی جسم میں ان لطائف کی ڈیوٹیاں", "link": "functions-of-subleties-in-the-human-body" },
  { "text": "لفظ اللہ", "link": "the-word-allah" },
  { "text": "نور بنانے کا طریقہ", "link": "the-method-of-producing-divine-light" },
  { "text": "بابت مراقبہ", "link": "chapter-of-muraqibah-(transcendental-meditation)" },
  { "text": "بہشت کن لوگوں کے لئے ہے", "link": "who-deserves-the-paradise" },
  { "text": "تقویٰ کن لوگوں کے لئے ہے", "link": "which-individuals-qualify-for-taqwa-(piety)" },
  { "text": "تقدیر", "link": "taqdir-(the-fate)" },
  { "text": "تیسری ارواح", "link": "third-category-of-the-soul" },
  { "text": "سوچ تو ذرا تو کس آدم کی اولاد میں سے ہے؟", "link": "ponder-progeny-of-which-of-the-many-adams-do-you-come-from" },
  { "text": "مریخ میں انسانی زندگی ابھی بھی موجود ہے جبکہ سورج میں بھی آتشی مخلوق آباد ہے", "link": "human-life-exists-on-mars-creatures-made-of-fire-live-on-the-sun" },
  { "text": "آسمان پر روحیں حد سے زیادہ بن گئی تھیں:", "link": "the-number-of-souls-created-in-the-heaven-exceeded-the-limit" },
  { "text": "تصوف میں اہمیت قلب کو ہے", "link": "the-heart-has-the-central-and-very-important-role-in-spirituality" },
  { "text": "دین ِ الٰہی", "link": "the-religion-of-god" },
  { "text": "آخری زمانہ میں", "link": "in-the-end-times" },
  { "text": "روحوں کا دین", "link": "religion-of-souls" },
  { "text": "فرموداتِ گوہر شاہی 1", "link": "utterances-of-his-divine-eminence-ra-gohar-shahi-1" },
  { "text": "امام مہدی تمام مذاہب کی تجدید کرینگے", "link": "imam-mehdi-will-rejuvenate-all-the-religions" },
  { "text": "فرموداتِ گوہر شاہی 2", "link": "utterances-of-his-divine-eminence-ra-gohar-shahi-2" },
  { "text": "صراط مستقیم", "link": "sirat-al-mustaqeem-(straight-path-leading-to-god)" },
  { "text": "اللہ کا دوست", "link": "the-friend-of-god" },
  { "text": "گوہرشاہی کا عالمِ انسانیت کے لئے انقلابی پیغام", "link": "his-divine-eminence-gohar-shahis-revolutionary-message-to-humankind" },
  { "text": "گوہرشاہی کا عقیدہ", "link": "the-tenet-of-his-divine-eminence-gohar-shahi" },
  { "text": "رسولوں کے کلمے یہ ہیں", "link": "declaration-of-the-mursaleen-(the-grand-prophets)" },
  { "text": "چند محب ارواح کے چشم دید واقعے", "link": "eye-witness-accounts-of-a-few-selected-loving-souls" },
  { "text": "حضرت ریاض احمد گوہرشاہی کا شخصی تعارف", "link": "introduction-to-the-person-of-his-divine-eminence-ra-gohar-shahi" },
  { "text": "حضرت گوہرشاہی کی باطنی شخصیت کے چند حقائق", "link": "some-selected-features-of-his-divine-eminence-ra-gohar-shahis-esoteric-personality" },
  { "text": "’’جشن ِشاہی منانے کی وجوہات‘‘", "link": "what-jashan-e-shahi-and-the-reasons-why-it-is-celebrated" },
  { "text": "چاند اور سورج پر تصاویر کے بارے میں مکمل وضاحت", "link": "exhaustive-explanation-about-the-images-on-the-sun-and-the-moon" },
  { "text": "منجانب اللہ تصاویرِ گوہر شاہی کا ظہور", "link": "miraculous-images-of-his-divine-eminence-ra-gohar-shahi" },
  { "text": "چاند", "link": "moon" },
  { "text": "سورج", "link": "sun" },
  { "text": "خلاء", "link": "space" },
  { "text": "حجرِ اسود", "link": "black-stone" },
  { "text": "نبیولا", "link": "nebula" },
  { "text": "مریخ", "link": "mars" },
  { "text": "مریخ اوردیگر سیاروں پر شبیہ کا راز", "link": "an-insight-into-the-manifestation-of-human-images-in-the-moon-mars-and-various-other-planets" },
  { "text": "اپیل", "link": "appeal" },
  { "text": "شو مندر، عمر کوٹ", "link": "shivling" },
  { "text": "دیس پردیس اخبار لندن", "link": "des-pardes" },
  { "text": "کرشمۂ قدرت", "link": "a-divine-phenomenon" },
  { "text": "عیسیٰ علیہ السلام کی حضرت ریاض احمد گوہر شاہی سے امریکہ میں ملاقات", "link": "the-return-of-jesus-jesus-christ-meets-gohar-shahi-in-america" },
  { "text": "فرمان ِ گوہرشاہی", "link": "utterances-of-his-divine-eminence-ra-gohar-shahi-3" },
  { "text": "پروگرام", "link": "programs" },
  { "text": "تریاقِ قلب", "link": "taryaq-e-qalb" },
  { "text": "کتاب کی روشناس کے لئے چند اقتباس", "link": "the-excerpts-from-the-book-for-quick-awareness" }
];
